name: 'IA Pipeline Validation'
description: 'Valida etapas de CI/CD usando IA'

inputs:
  token:
    description: 'Token de acesso à API'
    required: true
  payload:
    description: 'Payload para validação'
    required: true
  api_url:
    description: 'URL da API de validação'
    required: false
    default: 'https://api.pipeline-validation.com'

runs:
  using: 'node16'
  main: 'index.js' 